version: '3.8'

services:
  backend:
    image: violturorg/startup-backend:latest
    container_name: backend
    restart: always
    pull_policy: always
    depends_on:
      - dataBase
    env_file:
      - .env
    networks:
      - app-net

  frontend:
    image: violturorg/qr-frontend:latest # Переконайтеся, що тут актуальний тег
    container_name: frontend
    restart: always # Тепер він буде працювати стабільно
    pull_policy: always
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      # ПРИБРАЛИ volume з фронтендом, він тепер не потрібен
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

  dataBase:
    image: postgres:17
    container_name: postgres17Dev
    restart: always
    env_file:
      - .env
    # ... інше без змін
    networks:
      - app-net

# Прибрали frontend_data з секції volumes, якщо він більше ніде не потрібен
volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge