version: '3.8'

services:
  backend:
    image: violturorg/startup-backend:latest
    container_name: backend
    restart: always
    pull_policy: always
    depends_on:
      - dataBase
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL_PROD}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-net

  frontend:
    image: violturorg/qr-frontend:latest
    container_name: frontend
    restart: always
    pull_policy: always
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

  dataBase:
    image: postgres:17
    container_name: postgres17Dev
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    # ... інше без змін
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge