spring:
  application:
    name: QrFlashBackend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/liquibase/master-main.yml
    enabled: true

tenant:
  db-url-template: "jdbc:postgresql://dataBase:5432/%s"

server:
  port: 8080

jwt:
  secret: xQATcBPX8Tgin165cvwlRr1d16rRPUdZho2YJlv09tg=

custom:
  datasource:
    urlConn: "jdbc:postgresql://dataBase:5432/%s"

minio:
  url: ${MINIO_ROOT_URL}
  accessKey: ${MINIO_ROOT_USER}
  secretKey: ${MINIO_ROOT_PASSWORD}
  bucket: ${MINIO_ROOT_BUCKET}
  ipServer: "http://13.48.55.202"
